import '../globals.css'
import Footer from "@/components/layout/footer"
import Header from "@/components/layout/header"

export const metadata = {
  title: 'WorkHub',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <body className=''>
      <Header/>
      {children}
      <Footer/>
    </body>
  )
}
