import '../globals.css'
import Footer from "@/components/layout/footer"
import Header from "@/components/layout/header"
import HeaderMobile from '@/components/layout/header-mobile'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <>
      <Header/>
      <HeaderMobile/>
      {children}
      <Footer/>
    </>
  )
}
