name: workFlow

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2.3.4

      - name: Configurar Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '22'

      - name: Instalar dependências and Build project
        run: |
          npm install
          npm run build

      - name: logging in Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build docker and publish image Docker
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          tags: ${{ secrets.DOCKER_USERNAME }}/WorkFlow-front
